### ISSUE TITLE
Raysession out of date and broken

### ISSUE THREAD

**Issue by thoth-amon** [geekosdawproject/geekosdaw-issues#78]
Version 0.11.1-1.467
Using Tumbleweed

The current version is out of date by two years, does not work (it opens but nothing works) and installing it caused an error where I was asked to downgrade python311-pyliblo when I tried to update my system. After that it throws up an extra error message about not being able to connect to the ray-daemon.

**Comment by KottV** [comment]
Thanks, raysession is updated to 0.14.2
Could you check if it work for you now, please.

**Comment by thoth-amon** [comment]
zypper is giving me the following error message

`Problem: nothing provides '/usr/bin/python3#' needed by the to be installed raysession-0.14.2-1.1.noarch`

**Comment by KottV** [comment]
should be fixed now

**Comment by thoth-amon** [comment]
The install works fine but the problem remains as before.  Have posted an issue on the raysession page

https://github.com/Houston4444/RaySession/issues/213

**Comment by Houston4444** [comment]
I am pretty sure that the problem comes from pyliblo version. As I mention it in the https://github.com/Houston4444/RaySession/blob/master/INSTALL.md , pyliblo must be taken from this fork: https://github.com/gesellkammer/pyliblo3
 because original upstream totally abandoned pyliblo and it is not compatible with new pythons versions anymore. Sorry for this.

I take this opportunity to say that I recommend to set python3-pyalsa (>= 1.2.5) as a dependency, this way ALSA MIDI ports can be shown in the patchbay.

**Comment by KottV** [comment]
thanks @Houston4444 for the info
I added pyliblo3 and all seems to work for me

and I'll try to make pyalsa package also

**Comment by thoth-amon** [comment]
Thank you to you both.  It's now working fine.
